name: 'Block labels'
description: 'Block PRs with any of the following labels.'
runs:
  using: 'node12'
  main: 'main.js'
inputs:
  labels:
    description: 'A JSON string of labels that will fail the PR.'
    required: true
    default: '["DO NOT MERGE"]'